name: Python application

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
        check-latest: true
        token: ${{ secrets.MY_PERSONAL_ACCESS_TOKEN }}
        update-environment: true
        allow-prereleases: false

    - name: Upgrade pip
      run: python -m pip install --upgrade pip

#    - name: Install dependencies
#      run: pip install -r Selenium/requirements.txt

    - name: Run tests
      run: |
        # Add your test commands here
        pytest
